### ISSUE TITLE
Verifying Argon2id hash

### ISSUE THREAD

**Issue by rc201612** [nitrachain/NitraLibSodium#1]
Hi, 

Do you have an example of verifying an Argon2id hash that was created using a salt (i.e. via ```Argon2id.CryptoArgon2id```)?

**Comment by VaduganathanP** [comment]
I created wrapper for curve and have not used the hash's. To my understanding you have to use the same method to generate using salt and password. Later compare the same with existing one (Argon2id.CryptoArgon2id). check this for password storage in case u need it https://download.libsodium.org/doc/password_hashing/the_argon2i_function.html
